---
title: '7: Backup in several formats'
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

See <https://bellecp.github.io/597-Data-Wrangling-Spring-2024/project.html#store-your-data-in-at-least-3-different-formats-e.g.-sqlite3-csv-excel>.

Describe your contributions below.

* * *

### Connect and Upload Backup Data to Mongo DB

- Data has been saved in 3 different formats in local. Now we upload a backup data to mongo db. Since mongo db stores data only in json format, we upload the cleaned json data in the mongo db database.
- This process is executed in 05_cleaning.qmd as the backup is taken right after the data is cleaned. Below is the code.

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
import pandas as pd
import json
##

uri = "mongodb+srv://fv121:Vasureddy2303@hw2cluster.zpracso.mongodb.net/?retryWrites=true&w=majority&appName=HW2Cluster"

##### **Create a new client and connect to the server**
client = MongoClient(uri, server_api=ServerApi('1'))

##### **Send a ping to confirm a successful connection**

try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

##### **Upload the data into the table **
db = client["premier-league-db"] # database name
collection = db["pl-data"] # table name

with open(r'..\Premier_league_Data_Cleaned_05.json', 'r') as file:
    data = json.load(file)

json_data = df.to_json(orient='records')
collection.insert_many(data, upsert=True)

for document in data:
    unique_key = {'_id': document['Unique_Key']}
    collection.update_one(unique_key, {'$set': document}, upsert=True)

print('DATA UPLOADED TO MONGO DB SUCCESSFULLY')
<<<<<<< HEAD
=======

>>>>>>> 277f615e263cba75e8de7ca0deb142b8a18a5544
